version: '3.8'

services:
  db:
    hostname: db
    build: 
      context: ./database
      dockerfile: Dockerfile
    image: db
    container_name: db_new
    restart: always
    environment:
      $MYSQL_DATABASE: project
      $MYSQL_USER: user
      $MYSQL_PASSWORD: test123
      $MYSQL_ROOT_PASSWORD: test1234
    expose:
      - "3306"
    ports:
      - "3306:3306"

  webui:
    hostname: webui
    build:
      context: ./webui2
      dockerfile: webui.Dockerfile
    image: webui
    container_name: webui
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    environment:
      $DATABASE_URL: mysql://remote:test1234@172.20.0.11:3306/project?schema=public
    networks:
      my-network:
        ipv4_address: 172.20.0.12
  
  # webserver:
  #   hostname: nginx
  #   build:
  #     context: ./webserver
  #     dockerfile: webserver.Dockerfile
  #   image: webserver
  #   container_name: webserver
  #   ports:
  #     - "80:80"
  #   networks:
  #     my-network:
  #       ipv4_address: 172.20.0.13

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
