version: '3.8'

services:
  db:
    hostname: db
    build: 
      context: ./database
      dockerfile: db.Dockerfile
    image: db
    container_name: db
    restart: always
    environment:
      $MYSQL_DATABASE: project
      $MYSQL_USER: user
      $MYSQL_PASSWORD: test123
      $MYSQL_ROOT_PASSWORD: test1234
    expose:
      - "3306"
    ports:
      - "3306:3306"

  webui:
    hostname: webui
    build:
      context: ./webui
      dockerfile: webui.Dockerfile
    image: webui
    container_name: webui
    depends_on:
      - db
    stdin_open: true
    tty: true
    ports:
      - "3001:3000"
    environment:
      $DATABASE_URL: mysql://remote:test1234@db:3306/project?schema=public

