version: '3'
services:
  webui:
    build:
      context: ./webui
      dockerfile: Dockerfile
    image: ajmosley345/468-project:webui

  webserver:
    build: 
      context: ./webserver
      dockerfile: Dockerfile
    image: ajmosley345/468-project:webserver