apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      labels:
        io.kompose.network/webui-db-my-network: "true"
        io.kompose.service: nginx
    spec:
      containers:
        - image: 127.0.0.1:30000/nginx-project
          name: nginx
          ports:
            - containerPort: 80
      hostname: nginx
      restartPolicy: Always
status: {}
