apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
spec:
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
        - command: ["/bin/sh", "-c"]
          args: ["sleep 10 && npx prisma db push --accept-data-loss && npx prisma db seed && yarn run dev"]
          env:
            - name: DATABASE_URL
              value: "mysql://root:test1234@mysql-service:3306/project?schema=public"
          image: ajmosley345/468-project:webui
          name: webui
          ports:
            - containerPort: 3000
          stdin: true
          tty: true
      hostname: webui
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - image: ajmosley345/468-project:webserver
          name: webserver
          ports:
            - containerPort: 80
      hostname: webserver
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "test1234"
        - name: MYSQL_DATABASE
          value: "project"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
      volumes:
      - name: init-script
        configMap:
          name: mysql-init-script
  strategy:
    type: Recreate
