apiVersion: v1
kind: Service
metadata:
  name: webui-service
  labels:
    app: webui
spec:
  type: NodePort
  ports:
    - name: webui
      port: 3001
      targetPort: 3001
      nodePort: 30090
  selector:
    app: webui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
spec:
  selector:
    matchLabels:
      app: webui
  replicas: 1
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - name: webui
        image: ajmosley345/468-project:webui
        command: ["/bin/bash"]
        args: ["/scripts/startup.sh"]
        ports:
        - containerPort: 3001
        volumeMounts:
        - name: startup
          mountPath: /scripts/
      volumes:
      - name: startup
        configMap:
          name: startup
          defaultMode: 0744
