apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  spec:
    containers:
      - image: 127.0.0.1:30000/nginx-project
        name: nginx
        ports:
          - containerPort: 80
    hostname: nginx
    restartPolicy: Always
